### ISSUE TITLE
Change response messages

### ISSUE THREAD

**Issue by etrupja** [etrupja/DotNetCore_EFCore_API#10]
Response messages should be changed to more meaningful ones.
Example:
Department can not be deleted since it has employees.

**Comment by Piotr1215** [comment]
An interesting concept to consider regarding deleting an employee is to set the record status to "deleted" or "archived" instead of physically removing the record from the database.

**Comment by etrupja** [comment]
Yes, would be better. 
I created a new issue about it: https://github.com/etrupja/NetCoreAPI/issues/11

**Comment by etrupja** [comment]
@Piotr1215 changes were added. Base repository was extended with 4 new methods. New changes have been applied to controllers as well. 

        void SetStatusDeleted(T entity);
        void SetStatusActive(T entity);
        void SetStatusArchived(T entity);
        void SetStatusPending(T entity);
